# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build without Release

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build with Maven
      run: mvn -B -U package -T 2C
    - name: Archive artifacts (GeyserSM Spigot)
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: GeyserSkinManager (Spigot)
          path: spigot/target/GeyserSkinManager-Spigot.jar
    - name: Archive artifacts (GeyserSM Velocity)
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: GeyserSkinManager (Velocity)
          path: velocity/target/GeyserSkinManager-Velocity.jar

    - name: Archive artifacts (GeyserSM Bungee)
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: GeyserSkinManager (Bungeecord)
          path: bungeecord/target/GeyserSkinManager-BungeeCord.jar
